# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='upload',
            field=models.FileField(blank=True, upload_to='publications'),
        ),
    ]
