# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-14 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, choices=[('sem1', '1º Semester'), ('sem2', '2º Semester'), ('annual', 'Annual')], max_length=10)),
                ('period', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('nocturnal', 'Nocturnal')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('degree', models.CharField(blank=True, choices=[('graduation', 'Graduation'), ('master', 'Master'), ('doctoral', 'Doctoral')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField()),
                ('class_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.Class')),
            ],
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('lecture_note', models.TextField()),
                ('upload', models.FileField(blank=True, upload_to='lectures-notes')),
                ('download', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='course_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.Course'),
        ),
        migrations.AddField(
            model_name='class',
            name='course_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.CourseCode'),
        ),
        migrations.AddField(
            model_name='class',
            name='lecture_notes',
            field=models.ManyToManyField(blank=True, to='teaching.LectureNote'),
        ),
        migrations.AddField(
            model_name='class',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
