# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_auto_20170121_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='class',
            name='notice_board',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
