# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-26 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_auto_20170123_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLectureNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.RemoveField(
            model_name='class',
            name='lecture_notes',
        ),
        migrations.RemoveField(
            model_name='class',
            name='period',
        ),
        migrations.AddField(
            model_name='class',
            name='class_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 1, 26, 18, 27, 48, 612163, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='classroom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='infobox_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='duration',
            field=models.CharField(blank=True, choices=[('sem1', 'S1'), ('sem2', 'S2'), ('annual', 'Annual')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coursecode',
            name='degree',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], max_length=10),
        ),
        migrations.AddField(
            model_name='classlecturenotes',
            name='class_lecture_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.Class'),
        ),
        migrations.AddField(
            model_name='classlecturenotes',
            name='lecture_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.LectureNote'),
        ),
    ]
