# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-26 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0008_auto_20170126_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='notice_board',
            field=models.TextField(blank=True, null=True),
        ),
    ]
