# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-26 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0009_auto_20170126_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='notice_board',
            field=models.TextField(blank=True, default='text'),
            preserve_default=False,
        ),
    ]
