# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-26 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0010_auto_20170126_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassLectureNotes',
            new_name='ClassLectureNote',
        ),
    ]
