# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-27 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0012_classlecturenote_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlecturenote',
            name='download',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecturenote',
            name='download',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
