# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-27 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0013_auto_20170127_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlecturenote',
            old_name='class_lecture_note',
            new_name='class_user',
        ),
    ]
