# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0014_auto_20170127_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlecturenote',
            name='lecture_note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teaching.LectureNote'),
            preserve_default=False,
        ),
    ]
