# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0015_auto_20170127_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecode',
            name='degree',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], max_length=15),
        ),
    ]
