# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0016_auto_20170128_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='class',
            name='duration',
        ),
    ]
