# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-02 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0017_auto_20170130_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlecturenote',
            options={'ordering': ['-position']},
        ),
    ]
