# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-18 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0019_auto_20170318_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['date']},
        ),
    ]
