# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-29 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0020_auto_20170318_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['-date']},
        ),
    ]
